# Generated by Django 4.2.30 on 2026-05-11 14:03

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email Address')),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('pan_number', models.CharField(blank=True, max_length=10, null=True, verbose_name='PAN Number')),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('is_email_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FinancialYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=10, unique=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Financial Year',
                'verbose_name_plural': 'Financial Years',
                'ordering': ['-year'],
            },
        ),
        migrations.CreateModel(
            name='SalaryDetail',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('age_group', models.CharField(choices=[('below_60', 'Below 60 years'), ('60_to_80', '60 to 80 years (Senior Citizen)'), ('above_80', 'Above 80 years (Super Senior Citizen)')], default='below_60', max_length=20)),
                ('basic_salary', models.DecimalField(decimal_places=2, default=0, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('hra_received', models.DecimalField(decimal_places=2, default=0, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='HRA Received')),
                ('special_allowance', models.DecimalField(decimal_places=2, default=0, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('lta', models.DecimalField(decimal_places=2, default=0, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Leave Travel Allowance')),
                ('bonus', models.DecimalField(decimal_places=2, default=0, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('other_income', models.DecimalField(decimal_places=2, default=0, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('rent_paid', models.DecimalField(decimal_places=2, default=0, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Annual Rent Paid')),
                ('is_metro_city', models.BooleanField(default=False, verbose_name='Living in Metro City?')),
                ('deduction_80c', models.DecimalField(decimal_places=2, default=0, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('150000'))], verbose_name='Section 80C (PPF, ELSS, LIC, etc.)')),
                ('deduction_80d', models.DecimalField(decimal_places=2, default=0, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100000'))], verbose_name='Section 80D (Medical Insurance)')),
                ('deduction_80e', models.DecimalField(decimal_places=2, default=0, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Section 80E (Education Loan Interest)')),
                ('deduction_80g', models.DecimalField(decimal_places=2, default=0, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Section 80G (Donations)')),
                ('home_loan_interest', models.DecimalField(decimal_places=2, default=0, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('200000'))], verbose_name='Home Loan Interest (Section 24)')),
                ('nps_contribution', models.DecimalField(decimal_places=2, default=0, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('50000'))], verbose_name='NPS Contribution (Section 80CCD)')),
                ('professional_tax', models.DecimalField(decimal_places=2, default=0, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Professional Tax')),
                ('standard_deduction', models.DecimalField(decimal_places=2, default=75000, max_digits=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('financial_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salary_records', to='tax_calculator.financialyear')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salary_details', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Salary Detail',
                'verbose_name_plural': 'Salary Details',
                'ordering': ['-created_at'],
                'unique_together': {('user', 'financial_year')},
            },
        ),
        migrations.CreateModel(
            name='TaxCalculation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('old_regime_gross_income', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('old_regime_total_deductions', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('old_regime_taxable_income', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('old_regime_tax', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('old_regime_cess', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('old_regime_total_tax', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('new_regime_gross_income', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('new_regime_total_deductions', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('new_regime_taxable_income', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('new_regime_tax', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('new_regime_cess', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('new_regime_total_tax', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('recommended_regime', models.CharField(default='new', max_length=20)),
                ('tax_savings', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('calculated_at', models.DateTimeField(auto_now=True)),
                ('salary_detail', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tax_calculation', to='tax_calculator.salarydetail')),
            ],
            options={
                'verbose_name': 'Tax Calculation',
                'verbose_name_plural': 'Tax Calculations',
            },
        ),
    ]
